#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require "halunke/lexer"
require "halunke/nodes"

module Halunke
  class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 46)

def parse(code)
  @tokens = Lexer.new.tokenize(code)
  do_parse
end

def next_token
  @tokens.shift
end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     7,     8,     9,     6,    12,     5,    16,    10,    11,     7,
     8,     9,     6,    17,     5,    19,    10,    11,     7,     8,
     9,     6,   nil,     5,   nil,    10,    11,     7,     8,     9,
     6,   nil,     5,   nil,    10,    11,     7,     8,     9,     6,
   nil,     5,   nil,    10,    11 ]

racc_action_check = [
     0,     0,     0,     0,     1,     0,    12,     0,     0,     3,
     3,     3,     3,    14,     3,    18,     3,     3,     5,     5,
     5,     5,   nil,     5,   nil,     5,     5,     6,     6,     6,
     6,   nil,     6,   nil,     6,     6,    15,    15,    15,    15,
   nil,    15,   nil,    15,    15 ]

racc_action_pointer = [
    -2,     4,   nil,     7,   nil,    16,    25,   nil,   nil,   nil,
   nil,   nil,     6,   nil,     5,    34,   nil,   nil,     9,   nil ]

racc_action_default = [
    -2,   -12,    -1,    -2,    -4,    -2,   -12,    -7,    -8,    -9,
   -10,   -11,   -12,    -3,   -12,    -2,    20,    -5,   -12,    -6 ]

racc_goto_table = [
     2,     1,    15,    13,   nil,    14,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18 ]

racc_goto_check = [
     2,     1,     3,     2,   nil,     2,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,     0,    -4,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 12, :_reduce_1,
  0, 13, :_reduce_2,
  2, 13, :_reduce_3,
  1, 14, :_reduce_none,
  3, 14, :_reduce_5,
  4, 14, :_reduce_6,
  1, 15, :_reduce_7,
  1, 15, :_reduce_8,
  1, 15, :_reduce_9,
  1, 15, :_reduce_10,
  1, 15, :_reduce_11 ]

racc_reduce_n = 12

racc_shift_n = 20

racc_token_table = {
  false => 0,
  :error => 1,
  :NUMBER => 2,
  :STRING => 3,
  :BAREWORD => 4,
  :OPEN_PAREN => 5,
  :CLOSE_PAREN => 6,
  :OPEN_CURLY => 7,
  :CLOSE_CURLY => 8,
  :OPERATOR => 9,
  :UNASSIGNED_BAREWORD => 10 }

racc_nt_base = 11

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NUMBER",
  "STRING",
  "BAREWORD",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPERATOR",
  "UNASSIGNED_BAREWORD",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 14)
  def _reduce_1(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 18)
  def _reduce_2(val, _values, result)
     result = Nodes.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 19)
  def _reduce_3(val, _values, result)
     result = Nodes.new([val[0]]).concat(val[1]) 
    result
  end
.,.,

# reduce 4 omitted

module_eval(<<'.,.,', 'grammar.y', 24)
  def _reduce_5(val, _values, result)
     result = Halunke::FunctionNode.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 25)
  def _reduce_6(val, _values, result)
     result = Halunke::MessageSendNode.new(val[1], MessageNode.new(val[2].nodes)) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 29)
  def _reduce_7(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 30)
  def _reduce_8(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 32)
  def _reduce_9(val, _values, result)
     result = BarewordNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 33)
  def _reduce_10(val, _values, result)
     result = BarewordNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 34)
  def _reduce_11(val, _values, result)
     result = UnassignedNode.new(BarewordNode.new(val[0])) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Halunke
