#!/usr/bin/env ruby

require "halunke/interpreter"
require "readline"

interpreter = Halunke::Interpreter.new

if ARGV.length == 0
  puts "Halunke REPL. Ctrl+d to quit"
  while (line = Readline.readline(">> "))
    begin
      value = interpreter.eval(line, repl: true)
      puts "=> #{value}" unless value.nil?
    rescue Exception => e
      puts "An Error Occurred: #{e.message}"
    end
  end
else
  interpreter.eval(File.read(ARGV[0]))
end
