#!/usr/bin/env ruby

require "halunke/interpreter"
require "readline"

interpreter = Halunke::Interpreter.new

puts "Halunke REPL. Ctrl+d to quit"
while (line = Readline.readline(">> ", true))
  value = interpreter.eval(line)
  puts "=> #{value}"
end
