#!/usr/bin/env ruby

require "halunke/interpreter"
require "readline"

interpreter = Halunke::Interpreter.new

puts "Halunke REPL. Ctrl+d to quit"
while (line = Readline.readline(">> ", true))
  begin
    value = interpreter.eval(line)
    puts "=> #{value}"
  rescue Exception => e
    puts "An Error Occurred: #{e.message}"
  end
end
